[versions]
junit-jupiter = "5.12.1"
jms-api       = "3.1.0"
activemq      = "2.41.0"
logback       = "1.5.18"
slf4j         = "2.0.17"

[libraries]
junit-jupiter   = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
jakarta-jms     = { module="jakarta.jms:jakarta.jms-api", version.ref="jms-api" }
artemis-client  = { module="org.apache.activemq:artemis-jakarta-client", version.ref="activemq" }
logback-core    = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
slf4j-api       = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
